### ISSUE TITLE
Melpa upload

### ISSUE THREAD

**Issue by bhipple** [jwiegley/nix-update-el#4]
I went to add this nice package to the [spacemacs nixos layer](http://spacemacs.org/layers/+os/nixos/README.html), but discovered it's not available for download off melpa.  I see in [your dotfiles](https://github.com/jwiegley/dot-emacs/blob/f5d88aece4a68f0b21d4ced6f5976f88d5a974d2/.gitmodules#L31-L33) you're using `use-package` with a file checked out in a git submodule, but some users may want to get it through a package manager (even if that package manager is not deterministic or repeatable!).  Would you be willing to upload it for convenient installation for those users?

I haven't actually uploaded a package to melpa before, but it appears that all we need is [this](https://github.com/bhipple/melpa/commit/ab4fd36f6c74132eb954280ab0ddf460f14f78d6).  However, it looks like melpa requires packages distributed on it to be licensed under a [GPL-compatible license](https://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses).  Would you be willing to consider putting a license on this package?

Update: I see it's licensed with GPLv2 already, so now all that remains is to fix the `package-lint` and checkdoc errors to comply with melpa standards.  Will send a PR.

**Comment by matthewbauer** [comment]
:+1: To this! We would also welcome integrating it into [nix-mode](https://github.com/NixOS/nix-mode)

**Comment by bhipple** [comment]
Oh my mistake; the license is specified as GPLv2 already in the source code comment! 
 
https://github.com/jwiegley/nix-update-el/blob/master/nix-update.el
